<?php /* Smarty version 2.6.14, created on 2015-04-16 10:23:05
         compiled from /home/www/autocom.net.ua/www/_debug/mailllist_tmp_1429168984.tpl */ ?>
<h3>Здравствуйте,&nbsp;</h3>
<div class="news_caption2" style="margin: 0px; padding: 0px; color: #5f5f5f; font-family: Arial, Tahoma, Verdana, sans-serif; font-size: 12px; line-height: 18px; background-color: #f5f6f5;">
<h2 style="margin: 0px 0px 10px; padding: 8px 10px; font-family: Georgia, Arial; font-size: 17px; color: #2f2f2f; font-weight: normal; font-style: italic; line-height: 17px; border: 1px solid transparent; border-radius: 5px; position: relative; background: #e7e7e7;">ВНИМАНИЕ ! ИЗМЕНЕНИЕ В ДОСТАВКЕ ПО РЕГИОНУ UAE !!!</h2>
</div>
<div class="news_fulltext" style="margin: 0px; padding: 0px; color: #5f5f5f; font-family: Arial, Tahoma, Verdana, sans-serif; font-size: 12px; line-height: 18px; background-color: #f5f6f5;">
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">Доставка запчастей из региона UAE :&nbsp;</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">&nbsp;Доставка по данному направлению осуществляется &nbsp;авиа-перевозкой и морем. Стоимость &nbsp;расценивается следующим образом:</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">&nbsp;</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">негабаритные позиции - 7$/1кг.</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">&nbsp;</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">габаритные позиции (фара , крыло , бампер ,капот , крыша - 12$/1кг.</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">&nbsp;</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">контейнерная доставка 4,5 $ / 1 кг физического веса в независимости от объема детали .</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">&nbsp;</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">ВНИМАНИЕ ! ЦЕНА В ПРАЙСЕ ПО РЕГИОНУ ОАЭ УКАЗАНА БЕЗ УЧЕТА ФИЗИЧЕСКОГО ВЕСА ДЕТАЛИ , ФИЗИЧЕСКИЙ ВЕС ВЫ МОЖЕТЕ УВИДЕТЬ ОТДЕЛЬНО В КОЛОНКЕ " СПРАВКА "</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">СТОИМОСТЬ ДОСТАВКИ ВЫСТАЛЯЕТСЯ ОТДЕЛЬНО В СЧЕТЕ И СПИСЫВАЕТСЯ С БАЛАНСА !</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">&nbsp;</div>
<div id="_mcePaste" style="margin: 0px; padding: 0px; position: absolute; left: -10000px; top: 0px; width: 1px; height: 1px; overflow: hidden;">&nbsp;</div>
<p style="margin: 0px 0px 10px; padding: 0px;"><em style="margin: 0px; padding: 0px;">Доставка запчастей из региона UAE :&nbsp;&nbsp;Доставка по данному направлению осуществляется &nbsp;авиа-перевозкой и морем. Стоимость расценивается следующим образом:</em><br style="margin: 0px; padding: 0px;" /><br style="margin: 0px; padding: 0px;" /><span style="margin: 0px; padding: 0px; color: #ff0000;"><strong style="margin: 0px; padding: 0px;"><em style="margin: 0px; padding: 0px;">негабаритные позиции - 7$/1кг.</em></strong></span><br style="margin: 0px; padding: 0px;" /><br style="margin: 0px; padding: 0px;" /><span style="margin: 0px; padding: 0px; color: #ff0000;"><strong style="margin: 0px; padding: 0px;"><em style="margin: 0px; padding: 0px;">габаритные позиции (фара , крыло , бампер ,капот , крыша - 12$/1кг.</em></strong></span><br style="margin: 0px; padding: 0px;" /><br style="margin: 0px; padding: 0px;" /><span style="margin: 0px; padding: 0px; color: #ff0000;"><strong style="margin: 0px; padding: 0px;"><em style="margin: 0px; padding: 0px;">контейнерная доставка 4,5 $ / 1 кг физического веса в независимости от объема детали .</em></strong></span><br style="margin: 0px; padding: 0px;" /><br style="margin: 0px; padding: 0px;" /><strong style="margin: 0px; padding: 0px;">ВНИМАНИЕ !&nbsp;<span style="margin: 0px; padding: 0px; color: #ff0000;">ЦЕНА В ПРАЙСЕ ПО РЕГИОНУ ОАЭ УКАЗАНА БЕЗ УЧЕТА ФИЗИЧЕСКОГО ВЕСА ДЕТАЛИ</span>&nbsp;, ФИЗИЧЕСКИЙ ВЕС ВЫ МОЖЕТЕ УВИДЕТЬ ОТДЕЛЬНО В КОЛОНКЕ " СПРАВКА ", СТОИМОСТЬ ДОСТАВКИ ВЫСТАЛЯЕТСЯ ОТДЕЛЬНО В СЧЕТЕ И СПИСЫВАЕТСЯ С БАЛАНСА !</strong><br style="margin: 0px; padding: 0px;" />&nbsp;</p>
</div>
<div class="news_bottom_date" style="margin: 10px 0px 0px; padding: 0px; font-style: italic; font-size: 12px; color: #5f5f5f; font-family: Arial, Tahoma, Verdana, sans-serif; line-height: 18px; background-color: #f5f6f5;">16 апреля 2015</div>
<p>&nbsp;</p>